/**
 * List of Actions definitions
 *  
 * */
// Gifts
export const GET_GIFTS_SUCCESS = 'GET_GIFTS_SUCCESS';
export const CREATE_GIFT_SUCCESS = 'CREATE_GIFT_SUCCESS';
export const READ_GIFT_SUCCESS = 'READ_GIFT_SUCCESS';
export const UPDATE_GIFT_SUCCESS = 'UPDATE_GIFT_SUCCESS';
export const DELETE_GIFT_SUCCESS = 'DELETE_GIFT_SUCCESS';

// Categories
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const CREATE_CATEGORY_SUCCESS = 'CREATE_CATEGORY_SUCCESS';
export const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';

// Items
export const GET_ITEMS_SUCCESS = 'GET_USERS_SUCCESS';
export const DELETE_ITEM_SUCCESS = 'DELETE_USER_SUCCESS';

// Search
export const FILTER_ITEM = 'FILTER_ITEM';
